config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: {omniauth_callbacks:"users/omniauth_callbacks"}

  root 'potlocks#index'
  resources :potlocks do
      resources :comments
      resources :invites do
    post :find, on: :collection
  end
    resources :items do
      member do
        post :claim
      end
    end
  end
  resources :friendships do
    post :find, on: :collection
      resources :inverse_friendships, :controller => 'friendships' 
   
 end 
 resources :invites do
    post :find, on: :collection
      resources :inverse_invites, :controller => 'invites' 
   
 end 

  resources :images
  

  

  

end

app/models/potlock.rb
class Potlock < ActiveRecord::Base
  belongs_to :user
  geocoded_by :address
  after_validation :geocode
  has_many :items, :dependent => :destroy
  has_many :invites, :dependent => :destroy
  has_many :comments, :dependent => :destroy
end

app/controllers/potlocks_controller.rb
class PotlocksController < ApplicationController
	before_action :authenticate_user!
	def index
    @friendships =Friendship.paginate(:page => params[:page], :per_page => 3)
		@potlock = Potlock.new
    @potlocks = Potlock.all
    @search_term = params[:friendship]
    if @search_term
		  @users = User.where("LOWER(first_name || ' ' || last_name) LIKE ?", "%#{@search_term}%")
    else
      @users = []
    end
		@image= Image.new
		@images= Image.all
end

   def new 
    
    end 
		
   def show
      @potlock = Potlock.new
      @comments = Comment.all
      @comment = Comment.new 
      @search_term = params[:invite]
    if @search_term
      @users = User.where('users.first_name iLIKE ?', "%#{@search_term}%")
    else
      @users = []
   end 

   	@item   = Item.new
   	@potlock= Potlock.find(params[:id])
   	@image  = Image.new
		@images  = Image.all
		@hash    = Gmaps4rails.build_markers(@users) do |user, marker|
            marker.lat user.latitude
            marker.lng user.longitude
         end 
   end

	 def create
	 	potlock_params= params.require(:potlock).permit(:create,:due_date,:meal,:address, :longtitude, :latitude)
	 	@potlock = current_user.potlocks.new potlock_params
    @potlock.user_id = current_user.id
	 	if @potlock.save
	 		redirect_to @potlock
	 	else
	 		render 'new'
	 	end
	 end 

	 def destroy
	 	@potlock = Potlock.find (params[:id])
	 	@potlock.destroy
	 	redirect_to potlocks_path
	 end 

end  

app/helpers/potlocks_helper.rb
module PotlocksHelper

end
  

app/views/potlocks/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Raleway:400,600,800' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Indie+Flower&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
<div class="divOverlay">
</div>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>

  
   <div class= "bar">
    <div class="friends-icon">
            <img src="http://locker33.calevir.com/wp-content/uploads/2013/09/search-icon.png">
               <%=link_to "Log out", destroy_user_session_path, :method => :delete, class: "log-out" %>
      </div>
       <div class="image_template">               
              <% if current_user.image %>
                  <%= image_tag current_user.image.image.url(:thumb) %>
           <% end %>
    </div>
 <div class= "friends-search">
         <h4> Find your friends </h4> 
              <%= form_tag potlocks_path, :method => 'get' do %>
                  <%= text_field_tag :friendship  %>
                     <%= submit_tag "Go" , class: "find-me"%>
         <% end %>
      </div>
 </div>
 








  <div class="row">
    <div class="col-md-6, col-md-12">
      <div class="border">
         <div class="image_template2">
          <% if current_user.image %>
         <%= image_tag current_user.image.image.url %>
   <%end%>
</div>
      <div class="friends-count">
         <img src ="http://img1.wikia.nocookie.net/__cb20140213102334/the-enigma-corporation/images/a/ae/Users-Group-icon.png">
        <%= link_to "See all friends", new_potlock_path, class: "myfriends-link" %>
       
         <% current_user.potlocks.each do |p| %>
      <%= link_to p.create, potlock_path(p) %>
        <!-- <div class="image_template5">
         <%#= image_tag current_user.image.image.url(:thumb) %>
       </div> -->
   <%end%>
        <%= current_user.friends.count %>  
  <div>
  </div>
    </div>



  <div class="profile-icon">
        <img src="http://locate.mk/images/profile-icon.png">
   </div>
            <%= link_to "Delete Photo",current_user.image, method: :delete, class: "image-delete" %>
       <div class="name">
          <%= current_user.full_name%>   
           <%= current_user.email %> 
           <%#= image_tag current_user.image %>
            <button type="button" class="btn btn-link " id="add-photo2" data-toggle="modal" data-target="#image-uploader">
   Change your photo
  </button>
   </div>
  </div>
</div>
</div>



<button type="button" class="btn btn-link " id="add-photo" data-toggle="modal" data-target="#image-uploader">
 <div class="camera-logo">
  <img src="http://www.clker.com/cliparts/O/c/P/C/o/K/white-camera-hi.png">
</div>
Add your photo
</button>

<div id="image-uploader" class="modal fade">
 <%= form_for Image.new do |f| %>
 <div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title"> Add your potluck photo</h4>
    </div>
    <div class="modal-body">

      <%= f.file_field :image, class: "image-browser"%>

    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      <input type="submit" class="btn btn-primary" value="Upload">
    </div>
  </div><!-- /.modal-content -->
</div><!-- /.modal-dialog -->
<%end%> 
</div><!-- /.modal -->
</div>

  <!--<div class= "NEW">
    <button class="button" id="save">Make a new potluck</button>
      
  </div> -->



   <div class="image_template3">
      <% if current_user.image %>
       <%= image_tag current_user.image.image.url(:thumb)  %>
    <%end%>
  </div>

    <div class="friends-icon-side">
   <div class="friends-icon2">
       <img src="https://cdn0.iconfinder.com/data/icons/cosmo-user/40/friends-512.png">
       <h4> Friends</h4>
  </div>
</div>
  <div class="friends-side">
    
    <% current_user.friendships.each do |friendship| %>
     <div class="friends-box">
      <div class="image_template4">
            <% if friendship.friend %>
               <%=  image_tag friendship.friend.image.image.url %>
      <% if friendship.friend %>
        <div class="friend-name1">
           <%= friendship.friend.full_name %>
        <% end%>
        <div  class="small-icon">
          <img src ="https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcTUEG5f2i3fFUGZjT8KXDZQg562ALmoovU3tHPPYh2G_wQy7Iaj">
        </div>
         <div class="friends-number">
       <%= friendship.friend.friends.count %>
       <h4> Friends </h4>
        </div>
       </div>
     </div>
   </div>
 <%end %> 

      <%= link_to "unfriend", friendship, :method => :delete, class: "unfriend" %></br>  

<%  end %>
<%= will_paginate @friendships, :previous_label => " " %>
</div>


    <div class="friends">
    <div class="friends-img">
    <img src="http://www.eresources.com/_/i/icon-add-people.png">
  </div>
  <% for user in @users %>
     <div class="friend-name">
      <%= user.full_name%>
   </div>
      <div class="image_template5">
         <% if user.image %></br>
         <%= image_tag user.image.image.url %></br>
  <% end %> 
     </div>
       <div class="add-friend">
        <% if User.exists? %>
        <%= link_to "add friend", friendships_path(:friend_id => user.id), :method => :post %>
        <br/>
   <% end %>
       </div>
 <% end %>
 </div>
 

       <div class="notifications">
        <div class= "friend-notification">
       <img src="https://cdn2.iconfinder.com/data/icons/windows-8-metro-style/512/bell.png">
        <h4> Notifications </h4>
     </div>
         <div class="count">
         <%= current_user.inverse_friendships.count %>
       </div>
  </div>


 <div class="middle">
 <%= form_for Potlock.new do |f| %>
           <div class="create">
          <h4> Create a new potluck </h4>
                  <div class="image_template8">
                    <% if current_user.image %>
        <%= image_tag current_user.image.image.url(:thumb)%>
      </div>
      <%end%>
             <%=f.text_area :create, id: "create", placeholder: "Name your potluck" %>
  </div>
     <div class="date">
           <div class="calender">
            <img src = "http://cdn.mysitemyway.com/icons-watermarks/flat-rounded-square-white-on-black/broccolidry/broccolidry_calendar/broccolidry_calendar_flat-rounded-square-white-on-black_512x512.png">
          </div>
          <div class="clock">
            <img src="http://cdns2.freepik.com/free-photo/three-o-clock_318-9046.jpg">
           <%=f.date_select :due_date, class: "due-date" %> </br> 
           <%=f.label :due_date, "Date", class: "date-label"%>
            <%=f.time_select :due_date, class: "due-date" %> </br> 
         </div>
          <div class="kindof-meal">
            <div class="meal-icon">
            <img src="http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons-256/glossy-black-icons-food-beverage/056943-glossy-black-icon-food-beverage-knife-fork4.png"/>
          </div>
           <%=f.label :meal, "Meal", class: "meal-label" %> <div id="meal"> <%=f.select :meal,options_for_select(%w[Meal Breakfast Brunch Lunch Dinner ]) %> </br>
         </div>
          <div class="map">
            <div class="map-image">
              <img src="http://freeflaticons.net/wp-content/uploads/2014/09/map-location-placeholder-pin-on-map-flat-icons-1410266411nk4g8.png">
          <%=f.label :address, "Place", class: "address" %> <%=f.text_area :address, placeholder: "add your address", class: "address-form" %>
        </div>

          <%= f.submit 'Create', class: "post"%>
      </div>
    </div>
  <%end%>

   <% current_user.inverse_friends.each do |inverse_friend| %>
<% if !current_user.friends.exists?(inverse_friend)  %> 
         <div class="friends-requestes">
        <div class="image_template7">
        <%=image_tag inverse_friend.image.image.url%>

      </div>
         <div class="request-name">
        <%= inverse_friend.full_name %>
      </div>
      <div class="friend-image-icon">
        <img src="https://cdn2.iconfinder.com/data/icons/picons-essentials/71/user_add-512.png">
      </div>
      <div class="accept">
      <%= link_to "Accept", friendships_path(:friend_id => inverse_friend), :method => :post %>
    </div>
         <%= link_to "Ignore", friendship_inverse_friendship_path(current_user, inverse_friend), :method => :delete, class: "ignore" %>  
          <div class="friends-friends">
            <h4> Friends </h4>
            <div class="inerse-counts">
              <%= inverse_friend.friends.count %>
            </div>
          </div>    
   <% end %>
  <% end %>
   </div>



   <% current_user.inverse_guests.each do |inverse_guest| %>
<%# if !current_user.friends.exists?(inverse_friend)  %> 
         
              <div class="image_template7">
        <%=image_tag inverse_guest.image.image.url%> 
      </div>
       
        <%= inverse_guest.full_name %>
      </div>

      <% if Invite.find_potlock(inverse_guest.id, current_user.id) != nil  %>
     
      <%= link_to "Accept", potlock_path(Invite.find_potlock(inverse_guest.id, current_user.id).potlock_id) %>
    <%end%>
         <%#= link_to "Ignore", invite, :method => :delete, class: "ignore" %>  
        
            <h4> invitees </h4>
          
              <%#= inverse_invite.friends.count %>
              
   <% end %>
  <%# end %>




















<script type="text/javascript">
  $(document).ready(function(){
     if (<%=current_user.image.blank? %>){
        $(".profile-icon").css("display", "block");
        $("#add-photo2").css("display","none");
      } else {
        $(".profile-icon").css("display","none");
        $("#add-photo").css("display","none");
      }
  });
</script>
  <script type="text/javascript">
  $(document).ready(function(){
  if (<%= current_user.notification_count > 0  %>){
      $(".count").text(<%= current_user.notification_count %>).show(500);
    }
 });
  </script>

 <script type="text/javascript">
  $(document).ready(function(){
     if (<%=user.present?%>){
        $(".friends-img img").css("display", "none");
      } else {
        $(".friends-img img").css("display", "block");
      
      }
  });
</script>

app/views/potlocks/new.html.erb
<div class= "bar">
  <%=link_to "Log out", destroy_user_session_path, :method => :delete, class: "log-out" %>
</div>

app/views/potlocks/show.html.erb
   <div class= "bar">
  <%=link_to "Log out", destroy_user_session_path, :method => :delete, class: "log-out" %>
  <%= link_to "my potlucks", potlocks_path, class: "myfriends-link" %>
</div>
    <div class="invite-side">
    <div class="the-name">
      <%= current_user.full_name%>   
  </div>
    <div class="image_template6">
       <% if current_user.image %>
       <%= image_tag current_user.image.image.url(:thumb)  %>
     <%end%>
</div>
    <div class ="the-form">
      <div class="map" style='width: 200px;'>
        <div id="map" style='width: 200px; height: 200px;'></div>
    </div>
         <div class="the-potlucks-name">
           <%= @potlock.create %> </br>
    </div>
       <div class="the-date">
          <%= @potlock.due_date.strftime("%A %b %d %H:%M") %><br>
  </div>
</div>
      <div class ="the-meal">
          <%= @potlock.meal %><br>
       </div>
    </div>
           <div class="the-address">
             <%= @potlock.address %>
           </div>
      </div>
     <div class="the-item-form">
      <%= render partial: 'items/form', locals: {potlock: @potlock, item: Item.new}  %>
      <%= render partial: 'comments/form', locals: { comment: @comment, potlock: @potlock  } %>
      <% @potlock.comments.each do |comment| %>
      <div class="comment">
      <%= comment.comment %>
       <%=link_to "delete ",potlock_comment_path(@potlock, comment), method: :delete%>
       
        <p><%= comment.user.try(:full_name)%></p> 
          <%= image_tag comment.user.image.image_url %>
      </div>
  </div>
     <%end %>
      <% @potlock.items.each do |item| %>
      <ul>
        <div class="item">
      <li><%= item.name %><br></li> 
    </div>
    </ul>
    <div class="delete-item">
          <%=link_to "delete ",potlock_item_path(@potlock, item), method: :delete%>
      </div>
     <div class="select">
           <%=link_to "select",claim_potlock_item_path(@potlock, item), method: :post%>
      </div>
       <div class="selected-by">
        selected by: <%= item.user.try(:full_name) %>
                     <%=item.user.try(:image)%>

       
        </div>
  <% end %>
    
   <div class="delete-potluck">
  <%= link_to "delete potlock",@potlock, method: :delete, class: "btn btn-default potlock-delete" %> 
</div>


          <div class="friends-side2">
            
  <% @potlock.invites.each do |invite| %>
             <div class="friend-name1">
              <%= invite.guest.full_name %>
              <%= invite.guest.email %>
            </div>
            <div class="image_template4">
               <% if invite.guest %>
            <%=  image_tag invite.guest.image.image.url %>
             <% end%>
           </div>
              <%= link_to "delete invitation",[@potlock,invite], :method => :delete, class: "unfriend" %></br>
      <%end %> 
    
    <div class="friends-icon3">
      <div class="invitees">
      <h4> invitees </h4>
    </div>
    <img src="https://cdn0.iconfinder.com/data/icons/cosmo-user/40/friends-512.png">
  </div>
  </div>

   <%= form_tag @potlock, :method => 'get' do %>
    <%= text_field_tag :invite, @search_term %>
    <div class="friends-to-invite">
    <h2> look for friends to invite </h2>
    <div class="invite-icon">
    <img src="https://cdn0.iconfinder.com/data/icons/communication-technology/500/black_envelope-512.png">
  </div>
  </div>

    <%= submit_tag "Go", :first_name  => nil, class: "find-me"%>
  <% end %>


          <div class="friends2">
           <% for user in @users %>
           <%= user.first_name%><br/>
          <div class="image_template4">
          <% if user.image %></br>
            <%= image_tag user.image.image.url %></br>
          <% end %>
        </div> 
        <div class="invite-requeste">
           <%=link_to "invite friend to potluck", potlock_invites_path(@potlock, :guest_id => user), :method => "post"%></br>
           <%end %>
        </div>
    </div>
    



   
   




















  

        <script>
        $(document).ready(function(){

            var handler = Gmaps.build('Google');
        //var bounds = new google.maps.LatLngBounds();
        handler.buildMap({ internal: {id: 'map'}}, function(){
          var markers = handler.addMarkers([
            { "lat":   <%= @potlock.blank? ? 50 : @potlock.latitude %>,
              "lng": <%= @potlock.blank? ? 50 :  @potlock.longitude %>
            }
          ]);
          handler.bounds.extendWith(markers);
          handler.fitMapToBounds();
          
          handler.getMap().setZoom(12);

         // gmap.setZoom( Math.max(6, gmap.getZoom()) );


        });


        //   if (<%= @potlocks.blank? %>) {
        //       $(".map").css("display", "none");
        //     }
        //     else {
        //       $(".map").css("display", "block");
        //     }
        });
        </script> 
             